### ISSUE TITLE
error

### ISSUE THREAD

**Issue by robertlevy** [grundic/confluence-page-copier#13]
I'm getting an error when running this and not really sure how to diagnose or fix it.

```
Traceback (most recent call last):
  File "C:\Users\rober\Downloads\confluence-page-copier-master\confluence-page-copier-master\copier.py", line 508, in <module>
    recursion_limit=args.recursion_limit
  File "C:\Users\rober\Downloads\confluence-page-copier-master\confluence-page-copier-master\copier.py", line 136, in copy
    skip_attachments=skip_attachments
  File "C:\Users\rober\Downloads\confluence-page-copier-master\confluence-page-copier-master\copier.py", line 115, in copy
    self._copy_attachments(source, page_copy_id)
  File "C:\Users\rober\Downloads\confluence-page-copier-master\confluence-page-copier-master\copier.py", line 347, in _copy_attachments
    attachment_comment=attachment_comment
  File "C:\Users\rober\Downloads\confluence-page-copier-master\confluence-page-copier-master\copier.py", line 363, in _create_attachment
    return self._process_attachment(url, attachment_name, attachment_content, attachment_type, attachment_comment)
  File "C:\Users\rober\Downloads\confluence-page-copier-master\confluence-page-copier-master\copier.py", line 376, in _process_attachment
    prepared_request = req.prepare()
  File "C:\Python27\lib\site-packages\requests\models.py", line 251, in prepare
    hooks=self.hooks,
  File "C:\Python27\lib\site-packages\requests\models.py", line 298, in prepare
    self.prepare_body(data, files, json)
  File "C:\Python27\lib\site-packages\requests\models.py", line 449, in prepare_body
    (body, content_type) = self._encode_files(files, data)
  File "C:\Python27\lib\site-packages\requests\models.py", line 152, in _encode_files
    fdata = fp.read()
AttributeError: 'NoneType' object has no attribute 'read'
```

**Comment by grundic** [comment]
Hello, @robertlevy.
First of all, sorry for late reply :( Got a lot of work...

Can you please give me a sample command that you are trying to execute?
There is definitely something wrong with attachments.
